<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFamilyRepository extends EntityRepository
{
    public function createAlphabeticalQueryBuilder()
    {
        return $this->createQueryBuilder('sub_family')
            ->orderBy('sub_family.name', 'ASC');
    }

    public function findAny()
    {
        return $this->createQueryBuilder('sub_family')
            ->OrderBy('sub_family.name','DESC')
            ->getQuery()
            ->getResult();
    }
}
