homepage:
    path: /
    defaults:
        _controller: App\Controller\MainController::homepageAction


easy_admin_bundle:
    resource: "../src/Controller/EasyAdmin/AdminController.php"
    type:     annotation
    prefix:   /easyadmin